name: mobile_tol_guard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: '>=3.0.0 <4.0.0'
# use flutter version : 3.27.3

dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  bloc: ^9.0.0
  camera: ^0.11.2
  convert: ^3.1.2
  dartz: ^0.10.1
  device_info_plus: ^11.3.0
  dio: ^5.8.0+1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  get_it: ^8.0.3
  image: ^4.5.4
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  intl: ^0.20.0
  intl_utils: ^2.8.11
  navigation_history_observer: ^1.1.1
  package_info_plus: ^8.3.0
  path: ^1.9.0
  permission_handler: ^12.0.1
  pointycastle: ^3.9.1
  pretty_json: ^2.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
  output_dir: lib/core/translator
  arb_dir: lib/core/translator/arb
flutter_assets:
  assets_path: assets/
  output_path: lib/core/util/
  filename: assets.dart
  field_prefix: null
