///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesEvent1 = 'assets/images/event1.jpg';
  static const String imagesEvent2 = 'assets/images/event2.jpg';
  static const String imagesEvent3 = 'assets/images/event3.jpg';
  static const String imagesEvent4 = 'assets/images/event4.jpeg';
  static const String imagesEvent5 = 'assets/images/event5.jpeg';
  static const String imagesIcHome = 'assets/images/ic_home.png';
  static const String imagesIcLogo = 'assets/images/ic_logo.png';
  static const String imagesIcMaps = 'assets/images/ic_maps.png';
  static const String imagesIcSettings = 'assets/images/ic_settings.png';
}
